### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by liyuzhu1984** [alibaba/packer-provider#46] opened 2018-10-22 07:37 UTC
panic: gob: registering duplicate names for *map[string]interface {}: "map[string]interface {}" != "*map[string]interface {}"

goroutine 1 [running]:
encoding/gob.RegisterName(0x204e6f6, 0x18, 0x2151ec0, 0xc42020a920)
        /usr/local/golang/src/encoding/gob/type.go:826 +0x4cc
encoding/gob.Register(0x2151ec0, 0xc42020a920)
        /usr/local/golang/src/encoding/gob/type.go:874 +0x127
github.com/hashicorp/packer/packer/rpc.init.0()
        /home/src/github.com/hashicorp/packer/packer/rpc/init.go:6 +0x41
github.com/hashicorp/packer/packer/rpc.init()
        <autogenerated>:1 +0x89
github.com/hashicorp/packer/packer/plugin.init()
        <autogenerated>:1 +0x5f
api/packer.init()
        <autogenerated>:1 +0x67
api.init()
        <autogenerated>:1 +0x5d
main.init()
        <autogenerated>:1 +0x4e

**Comment by liyuzhu1984** [comment] 2018-10-22 07:38
env centos7  golang1.9

**Comment by liyuzhu1984** [comment] 2018-10-31 08:09
no configuration file， i just run it after compile， and then panic。

**Comment by chhaj5236** [comment] 2018-10-31 09:09
@liyuzhu1984 How did you compile this provider? Since we do not encounter the issue you mentioned, more details would be helpful to reproduce.

**Comment by liyuzhu1984** [comment] 2018-11-05 03:09
import (
    "github.com/alibaba/packer-provider/alicloud-import"
    "github.com/alibaba/packer-provider/ecs"
    "github.com/hashicorp/packer/packer/plugin"
)

func NewPackerCtl() *PackerCtl {
    server.RegisterBuilder(new(ecs.Builder))
    server.RegisterPostProcessor(new(alicloudimport.PostProcessor))
    server.Serve()
}

i add the code to myself project,   so i can do packer by my program.  NewPackerCtl will be call in my   
init function.

**Comment by chhaj5236** [comment] 2018-11-07 01:49
@liyuzhu1984 This seems not a packer-provider issue. You might need more investigations about your project codes. I'll close this issue for now, if you found anything related to this provider, please let us know. Thanks for your contribution.

**Closed by chhaj5236** 2018-11-07 01:49 UTC
